FROM plebnet/plebnet
MAINTAINER plebnet

WORKDIR /root/tribler

# Open up RESTapi port to localhost of host system in which the container runs.
RUN sed -ie 's/"127.0.0.1"/"0.0.0.0"/g' /root/tribler/Tribler/Core/Modules/restapi/rest_manager.py

# Run tribler with plebnet settings on startup
CMD twistd -n plebnet -p 8085
