FROM ubuntu:16.04
MAINTAINER plebnet

WORKDIR /root

# This dockerfile combines all components needed to run plebnet.
# in its best practices https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#minimize-the-number-of-layers
# it is noted that one should have containers with one concern. 
# Maybe split these concerns later.

RUN apt update && apt install -y \
# General dependencies
	git \
# Tribler (headless) dependencies
	python-twisted \
	python-libtorrent \
	python-apsw \
	python-chardet \
	python-cherrypy3 \
	python-nacl \
	python-m2crypto \
	python-configobj \
	python-netifaces \
	python-leveldb \
	python-decorator \
	python-feedparser \
# Market community dependencies
	python-keyring \
	python-libnacl \
	python-ecdsa \
	python-pbkdf2 \
	python-requests \
	python-protobuf \
	python-socks \
	python-dnspython \
	python-jsonrpclib
	
ADD https://pypi.python.org/packages/63/31/6768a72cdca5dbd299ae798b690801e6c9c2f018332eec3c5fca79370dba/pyaes-1.6.0.tar.gz .
RUN tar -xvzf pyaes-1.6.0.tar.gz
WORKDIR pyaes-1.6.0
RUN python setup.py install

WORKDIR /root

# Install tribler
RUN git clone --recursive https://github.com/devos50/tribler
WORKDIR tribler
RUN git checkout market_community
RUN git submodule update --init --recursive electrum

WORKDIR Tribler
RUN git submodule update --init --recursive dispersy

WORKDIR /root/tribler

ENV TRIBLER_HOME="/root/tribler"

# Copy config and set market_community to true if using it.

CMD /bin/bash
