FROM ubuntu:16.04
MAINTAINER plebnet

WORKDIR /root

# Install tribler and its dependencies

RUN apt update && apt install -y \
# Tribler dependencies
	gconf2 \
	python2.7-minimal \
	libav-tools \
	libjs-excanvas \
	libsodium18 \
	libjs-mootools \
	libx11-6 \
	python-apsw \
	python-chardet \
	python-cherrypy3 \
	python-configobj \
	python-cryptography \
	python-decorator \
	python-feedparser \
	python-leveldb \
	python-libtorrent \
	python-matplotlib \
	python-m2crypto \
	python-netifaces \
	python-pil \
	python-twisted \
	python-pyqt5 \
	python-pyqt5.qtsvg \
	vlc

# Install tribler
ADD https://github.com/Tribler/tribler/releases/download/v7.0.0-rc1/tribler_7.0.0-rc1.deb .

RUN dpkg -i tribler_7.0.0-rc1.deb

RUN apt-get -f install

ENV TRIBLER_HOME="/usr/share/tribler"

CMD /bin/bash
