FROM ubuntu:16.04
MAINTAINER plebnet

WORKDIR /root

# Install tribler from git and its dependencies

# I do not guarantee properly working code for this file, but there were no errors 
# starting up tribler in headless mode using
# twistd -n tribler

RUN apt update && apt install -y \
# General dependencies
	git \
# Tribler (headless) dependencies
	python-twisted \
	python-libtorrent \
	python-apsw \
	python-chardet \
	python-cherrypy3 \
	python-nacl \
	python-m2crypto \
	python-configobj \
	python-netifaces \
	python-leveldb \
	python-decorator \
	python-feedparser

# Install tribler
RUN git clone --recursive https://github.com/tribler/tribler

ENV TRIBLER_HOME="/root/tribler"

CMD /bin/bash
